CREATE TABLE surah (
  id INTEGER PRIMARY KEY,
  namaArab VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  namaLatin VARCHAR(100),
  namaIndo VARCHAR(100),
  jumlahAyat INTEGER,
  tempatTurun ENUM('Makkiyah', 'Madaniyah')
);

INSERT INTO surah (id, namaArab, namaLatin, namaIndo, jumlahAyat, tempatTurun) VALUES
(1, 'الفاتحة', 'Al-Fatihah', 'Pembuka', 7, 'Makkiyah'),
(2, 'البقرة', 'Al-Baqarah', 'Sapi Betina', 286, 'Madaniyah'),
(3, 'آل عمران', 'Ali Imran', 'Keluarga Imran', 200, 'Madaniyah'),
(4, 'النساء', 'An-Nisa', 'Perempuan', 176, 'Madaniyah'),
(5, 'المائدة', 'Al-Maidah', 'Hidangan', 120, 'Madaniyah'),
(6, 'الأنعام', 'Al-Anam', 'Binatang Ternak', 165, 'Makkiyah'),
(7, 'الأعراف', 'Al-Araf', 'Tempat Tertinggi', 206, 'Makkiyah'),
(8, 'الأنفال', 'Al-Anfal', 'Rampasan Perang', 75, 'Madaniyah'),
(9, 'التوبة', 'At-Taubah', 'Pengampunan', 129, 'Madaniyah'),
(10, 'يونس', 'Yunus', 'Nabi Yunus', 109, 'Makkiyah'),
(11, 'هود', 'Hud', 'Nabi Hud', 123, 'Makkiyah'),
(12, 'يوسف', 'Yusuf', 'Nabi Yusuf', 111, 'Makkiyah'),
(13, 'الرعد', 'Ar-Rad', 'Guruh', 43, 'Madaniyah'),
(14, 'إبراهيم', 'Ibrahim', 'Nabi Ibrahim', 52, 'Makkiyah'),
(15, 'الحجر', 'Al-Hijr', 'Bukit Hijr', 99, 'Makkiyah'),
(16, 'النحل', 'An-Nahl', 'Lebah', 128, 'Makkiyah'),
(17, 'الإسراء', 'Al-Isra', 'Perjalanan Malam', 111, 'Makkiyah'),
(18, 'الكهف', 'Al-Kahf', 'Gua', 110, 'Makkiyah'),
(19, 'مريم', 'Maryam', 'Maryam', 98, 'Makkiyah'),
(20, 'طه', 'Ta Ha', 'Ta Ha', 135, 'Makkiyah'),
(21, 'الأنبياء', 'Al-Anbiya', 'Para Nabi', 112, 'Makkiyah'),
(22, 'الحج', 'Al-Hajj', 'Haji', 78, 'Madaniyah'),
(23, 'المؤمنون', 'Al-Muminun', 'Orang-orang Mukmin', 118, 'Makkiyah'),
(24, 'النور', 'An-Nur', 'Cahaya', 64, 'Madaniyah'),
(25, 'الفرقان', 'Al-Furqan', 'Pembeda', 77, 'Makkiyah'),
(26, 'الشعراء', 'Asy-Syuara', 'Para Penyair', 227, 'Makkiyah'),
(27, 'النمل', 'An-Naml', 'Semut', 93, 'Makkiyah'),
(28, 'القصص', 'Al-Qasas', 'Cerita', 88, 'Makkiyah'),
(29, 'العنكبوت', 'Al-Ankabut', 'Laba-laba', 69, 'Makkiyah'),
(30, 'الروم', 'Ar-Rum', 'Bangsa Romawi', 60, 'Makkiyah'),
(31, 'لقمان', 'Luqman', 'Luqman', 34, 'Makkiyah'),
(32, 'السجدة', 'As-Sajdah', 'Sujud', 30, 'Makkiyah'),
(33, 'الأحزاب', 'Al-Ahzab', 'Golongan yang Bersekutu', 73, 'Madaniyah'),
(34, 'سبأ', 'Saba', 'Kaum Saba', 54, 'Makkiyah'),
(35, 'فاطر', 'Fatir', 'Pencipta', 45, 'Makkiyah'),
(36, 'يس', 'Ya Sin', 'Ya Sin', 83, 'Makkiyah'),
(37, 'الصافات', 'As-Saffat', 'Barisan-barisan', 182, 'Makkiyah'),
(38, 'ص', 'Sad', 'Sad', 88, 'Makkiyah'),
(39, 'الزمر', 'Az-Zumar', 'Rombongan-rombongan', 75, 'Makkiyah'),
(40, 'غافر', 'Gafir', 'Yang Maha Pengampun', 85, 'Makkiyah'),
(41, 'فصلت', 'Fussilat', 'Yang Dijelaskan', 54, 'Makkiyah'),
(42, 'الشورى', 'Asy-Syura', 'Musyawarah', 53, 'Makkiyah'),
(43, 'الزخرف', 'Az-Zukhruf', 'Perhiasan', 89, 'Makkiyah'),
(44, 'الدخان', 'Ad-Dukhan', 'Kabut', 59, 'Makkiyah'),
(45, 'الجاثية', 'Al-Jasiyah', 'Yang Berlutut', 37, 'Makkiyah'),
(46, 'الأحقاف', 'Al-Ahqaf', 'Bukit-bukit Pasir', 35, 'Makkiyah'),
(47, 'محمد', 'Muhammad', 'Nabi Muhammad', 38, 'Madaniyah'),
(48, 'الفتح', 'Al-Fath', 'Kemenangan', 29, 'Madaniyah'),
(49, 'الحجرات', 'Al-Hujurat', 'Kamar-kamar', 18, 'Madaniyah'),
(50, 'ق', 'Qaf', 'Qaf', 45, 'Makkiyah'),
(51, 'الذاريات', 'Az-Zariyat', 'Angin yang Menerbangkan', 60, 'Makkiyah'),
(52, 'الطور', 'At-Tur', 'Bukit', 49, 'Makkiyah'),
(53, 'النجم', 'An-Najm', 'Bintang', 62, 'Makkiyah'),
(54, 'القمر', 'Al-Qamar', 'Bulan', 55, 'Makkiyah'),
(55, 'الرحمن', 'Ar-Rahman', 'Yang Maha Pengasih', 78, 'Madaniyah'),
(56, 'الواقعة', 'Al-Waqiah', 'Hari Kiamat', 96, 'Makkiyah'),
(57, 'الحديد', 'Al-Hadid', 'Besi', 29, 'Madaniyah'),
(58, 'المجادلة', 'Al-Mujadilah', 'Wanita yang Mengajukan Gugatan', 22, 'Madaniyah'),
(59, 'الحشر', 'Al-Hasyr', 'Pengusiran', 24, 'Madaniyah'),
(60, 'الممتحنة', 'Al-Mumtahanah', 'Wanita yang Diuji', 13, 'Madaniyah'),
(61, 'الصف', 'As-Saf', 'Barisan', 14, 'Madaniyah'),
(62, 'الجمعة', 'Al-Jumuah', 'Hari Jumat', 11, 'Madaniyah'),
(63, 'المنافقون', 'Al-Munafiqun', 'Orang-orang Munafik', 11, 'Madaniyah'),
(64, 'التغابن', 'At-Tagabun', 'Hari Dinampakkan Kesalahan', 18, 'Madaniyah'),
(65, 'الطلاق', 'At-Talaq', 'Talak', 12, 'Madaniyah'),
(66, 'التحريم', 'At-Tahrim', 'Mengharamkan', 12, 'Madaniyah'),
(67, 'الملك', 'Al-Mulk', 'Kerajaan', 30, 'Makkiyah'),
(68, 'القلم', 'Al-Qalam', 'Pena', 52, 'Makkiyah'),
(69, 'الحاقة', 'Al-Haqqah', 'Hari Kiamat', 52, 'Makkiyah'),
(70, 'المعارج', 'Al-Maarij', 'Tempat Naik', 44, 'Makkiyah'),
(71, 'نوح', 'Nuh', 'Nabi Nuh', 28, 'Makkiyah'),
(72, 'الجن', 'Al-Jin', 'Jin', 28, 'Makkiyah'),
(73, 'المزمل', 'Al-Muzzammil', 'Orang yang Berselimut', 20, 'Makkiyah'),
(74, 'المدثر', 'Al-Muddassir', 'Orang yang Berkemul', 56, 'Makkiyah'),
(75, 'القيامة', 'Al-Qiyamah', 'Hari Kiamat', 40, 'Makkiyah'),
(76, 'الإنسان', 'Al-Insan', 'Manusia', 31, 'Madaniyah'),
(77, 'المرسلات', 'Al-Mursalat', 'Malaikat yang Diutus', 50, 'Makkiyah'),
(78, 'النبأ', 'An-Naba', 'Berita Besar', 40, 'Makkiyah'),
(79, 'النازعات', 'An-Naziat', 'Malaikat yang Mencabut', 46, 'Makkiyah'),
(80, 'عبس', 'Abasa', 'Bermuka Masam', 42, 'Makkiyah'),
(81, 'التكوير', 'At-Takwir', 'Menggulung', 29, 'Makkiyah'),
(82, 'الانفطار', 'Al-Infitar', 'Terbelah', 19, 'Makkiyah'),
(83, 'المطففين', 'Al-Mutaffifin', 'Orang yang Curang', 36, 'Makkiyah'),
(84, 'الانشقاق', 'Al-Insyiqaq', 'Terbelah', 25, 'Makkiyah'),
(85, 'البروج', 'Al-Buruj', 'Gugusan Bintang', 22, 'Makkiyah'),
(86, 'الطارق', 'At-Tariq', 'Yang Datang di Malam Hari', 17, 'Makkiyah'),
(87, 'الأعلى', 'Al-Ala', 'Yang Paling Tinggi', 19, 'Makkiyah'),
(88, 'الغاشية', 'Al-Gasyiyah', 'Hari Pembalasan', 26, 'Makkiyah'),
(89, 'الفجر', 'Al-Fajr', 'Fajar', 30, 'Makkiyah'),
(90, 'البلد', 'Al-Balad', 'Negeri', 20, 'Makkiyah'),
(91, 'الشمس', 'Asy-Syams', 'Matahari', 15, 'Makkiyah'),
(92, 'الليل', 'Al-Lail', 'Malam', 21, 'Makkiyah'),
(93, 'الضحى', 'Ad-Duha', 'Waktu Dhuha', 11, 'Makkiyah'),
(94, 'الشرح', 'Asy-Syarh', 'Melapangkan', 8, 'Makkiyah'),
(95, 'التين', 'At-Tin', 'Buah Tin', 8, 'Makkiyah'),
(96, 'العلق', 'Al-Alaq', 'Segumpal Darah', 19, 'Makkiyah'),
(97, 'القدر', 'Al-Qadr', 'Kemuliaan', 5, 'Makkiyah'),
(98, 'البينة', 'Al-Bayyinah', 'Bukti Nyata', 8, 'Madaniyah'),
(99, 'الزلزلة', 'Az-Zalzalah', 'Guncangan', 8, 'Madaniyah'),
(100, 'العاديات', 'Al-Adiyat', 'Kuda Perang', 11, 'Makkiyah'),
(101, 'القارعة', 'Al-Qariah', 'Hari Kiamat', 11, 'Makkiyah'),
(102, 'التكاثر', 'At-Takasur', 'Bermegah-megahan', 8, 'Makkiyah'),
(103, 'العصر', 'Al-Asr', 'Masa', 3, 'Makkiyah'),
(104, 'الهمزة', 'Al-Humazah', 'Pengumpat', 9, 'Makkiyah'),
(105, 'الفيل', 'Al-Fil', 'Gajah', 5, 'Makkiyah'),
(106, 'قريش', 'Quraisy', 'Suku Quraisy', 4, 'Makkiyah'),
(107, 'الماعون', 'Al-Maun', 'Barang yang Berguna', 7, 'Makkiyah'),
(108, 'الكوثر', 'Al-Kausar', 'Nikmat yang Berlimpah', 3, 'Makkiyah'),
(109, 'الكافرون', 'Al-Kafirun', 'Orang-orang Kafir', 6, 'Makkiyah'),
(110, 'النصر', 'An-Nasr', 'Pertolongan', 3, 'Madaniyah'),
(111, 'المسد', 'Al-Masad', 'Gejolak Api', 5, 'Makkiyah'),
(112, 'الإخلاص', 'Al-Ikhlas', 'Ikhlas', 4, 'Makkiyah'),
(113, 'الفلق', 'Al-Falaq', 'Waktu Subuh', 5, 'Makkiyah'),
(114, 'الناس', 'An-Nas', 'Manusia', 6, 'Makkiyah');